print("Getting to know you")
print()
yourName=input("What's your name: ")
yourFood=input("What's your favorite food: ")
yourMusic=input("What's your music: ")
yourHome=input("Where do you live: ")
print()
print("You are " + yourName + ", You're probably wanting some " + yourFood + ", and youre definitely getting your groove on to " + yourMusic + " while living in " + yourHome)
print()
print("You are unstoppable, " + yourName + ". Your future is yours to control!")