yourName = input("What is your name, dear traveler? ")
favFood = input ("May I ask what your favorite meal is? ")
city = input("Very interesting, and where about do you live? ")
sport = input("you're quite the specimin, what kind of sports do you play? ")
job = input("Oh I never would have guessed, and what would your dream job be if you don't mind me asking? ")
print()
print("Well do I have a story for you!")
print("One passed down through the ages from times long forgotten.")
print()
print("\033[35m"+ "The Great Adventure of", yourName + "!")
print()
print("Once upon a time in the bustling city of", city, yourName, "was enjoying a delicious plate of", favFood, "at their favorite restaurant. As they savored each bite, they received a mysterious letter that would change their life forever.")
print()
print('The letter read: "Dear', yourName +", we have been watching your incredible skills in", sport +", and we believe you have the potential to be the greatest", job, "the world has ever seen.")
print("\033[0m")
shirt = input("Hmm it seems my eyes are failing me what color is that shirt of yours? ")
print()
print("Ahh thats right...where was I?")
print("Ahh yes")
print("\033[35m")
print("Meet us at the old, red barn on the outskirts of town at sunset. Wear your", shirt, "shirt, and bring your loyal friend, ")
print("\033[0m")
friend = input("what was your friends name again? ")
print("Right right," + "\033[35m", "bring your loyal friend,", friend, "and your most treasured possession, ")
print("\033[0m")
tresure = input("What would your most tresured possion be perhaps? ")
print("Oh that makes sense")
print("\033[35m")
print("And your most treasured possession,", tresure +'. This is the beginning of a thrilling adventure."')
print()
print("With curiosity in their heart,", yourName, "finished their meal and shared the news with", friend +". Together, they made their way to the old red barn at sunset,", tresure, "in hand.")
print()
print("As they entered the barn, they were greeted by a group of skilled mentors who shared their passion for", sport + ". They revealed that they were on a quest to uncover the next great", job + ", and they believed that", yourName, "was the chosen one.")
print()
print("Over the next few months,", yourName, "trained tirelessly, honing their skills and learning from the best. Their bond with", friend, "grew stronger, and their", shirt, "shirt became a symbol of their dedication.")
print("Finally, the day of the ultimate challenge arrived.", yourName, "faced competitors from all over the world in a grand tournament. With", tresure, "as their lucky charm, they pushed themselves to the limit and emerged victorious, earning the title of the world's greatest", job +".")
print("From that day forward,", yourName, "embarked on a thrilling adventure, traveling the world, inspiring others, and achieving greatness in their chosen path. Their journey was a testament to the power of passion, friendship, and believing in oneself.")
print("And so, the great adventure of", yourName, "became a legend in the city of", city, "a story told to inspire future generations to chase their dreams and turn them into reality.")